fix: update webpack peer dependency to ^4.37.0
When webpack-dev-server is run on any webpack version < 4.37, this error appears.

    [webpack-cli] TypeError: compiler.getInfrastructureLogger is not a function

This is because `compiler.getInfrastructureLogger` is introduced in webpack v4.37, therefore webpack-dev-server is not compatible with any version of webpack below it.